CREATE TABLE Magacin (
  ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  Naziv TEXT NOT NULL,
  Lokacija TEXT NOT NULL,
  PRIMARY KEY(ID)
)
ENGINE=InnoDB;

CREATE TABLE Roba (
  ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  Magacin_ID INTEGER UNSIGNED NOT NULL,
  Naziv TEXT NULL,
  Kolicina INTEGER UNSIGNED NULL,
  PRIMARY KEY(ID),
  INDEX Roba_FKIndex1(Magacin_ID),
  FOREIGN KEY(Magacin_ID)
    REFERENCES Magacin(ID)
      ON DELETE RESTRICT
      ON UPDATE CASCADE
)
ENGINE=InnoDB;